front/src/pages/Login/Login.tsx
front/tailwind.config.js

close #8 
- 학번, 비밀번호 입력
- 회원가입 링크 생성
api연결 테스트 전

♻️ Refactor/#8 비밀번호 입력 필드 추가 및 회원가입 링크 생성

---

front/src/components/Input.tsx
front/src/pages/SignUp/components/EmailVerification.tsx

#7 
- [Input에 text center 제거](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/6023f55cc409d64dcd2af160d21779a87e6e7f57)
- [EmailVerification margin bottom 제거](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/6586f45210b2820aec4736ace9dd068b5b37e5c9)

💄 Feat/#7 Signup 페이지 css 수정

---

front/src/pages/Login/Login.tsx

#8 
- [♻️ 학번 10자리 검증 로직 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/63fdd67eb1d98e07452b12a6e89795ce033314be)
- [♻️ 광운대학교로 타이틀 변경 및 로그인버튼 이름 변경](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/26e653e15b491c9eb0a5b51e0c974729da204d86)

♻️ Refactor/#8 학번 10자리 검증 로직 수정 및 광운대학교로 타이틀 변경

---

front/src/pages/MakeReservation/MakeReservation.tsx

#9
- [♻️ 강의실 예약시, 건물 정보도 같이 보내기](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/0b20e2167d527094606de31717513172cff8e469)
- [💄 건물 및 강의실 셀렉박스를 좌우로 배치](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/2fa4bb991aa457032b09178183456b0c8d01ec65)

♻️ Refactor/#9 강의실 예약시, 건물 정보도 같이 보내기

---

front/src/pages/SignUp/components/EmailVerification.tsx

#17 
- `${import.meta.env.VITE_API_URL}/api/sendEmail` 으로 요청 API 변경

🐛 Fix/#17 api 호출시 URL 변경

---

back/handlers/sendEmail.js

#23
[🔨 메일 내용 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/979b93ae2bb2e7df95e2ad8c73c8176ea3a6d7b4)

🔨 Refactor/#23 메일 내용 수정

---

front/src/pages/SignUp/components/EmailVerification.tsx

#24 
- [🔨 이메일 인증시 초 줄어드는 기능 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/542f2ef5493dbcdb9303ceff6265b1f00ef319d8)

🔨  Refactor/#24 이메일 인증시 초 줄어드는 기능 수정

---

back/db/reservation.js
back/routes/auth.js
back/routes/reservation.js

#28 
로그인할때 토큰, 예약할때 check-time api
토큰이 감싸져서 콘솔창에 뜸
check time api보낸 결과

✅ check-time api생성, 토큰 확인

---

back/db/student.js
back/routes/studentIdRouter.js
front/src/api/signup/checkIdAvailability.ts
front/src/api/signup/dto/signupDto.ts
front/src/api/signup/signup.ts
front/src/components/PageWrapper/CenteredPageWrapper.tsx
front/src/pages/Login/Login.tsx
front/src/pages/SignUp/SignUp.tsx
front/src/pages/SignUp/components/EmailVerification.tsx

#32 
- [CenteredPageWrapper 자식 요소 정렬을 중앙으로 변경](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/358e4ceaf69e7f450fa6b7dfd25e2226d121df98)
- [checkStudentId 경로 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/380173c0c2b58f1047c09c8ec053c9f15e9887f4)
- [회원가입 기능 구현 및 전화번호 입력 필드 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/05ca662e87961725487260e877f0c59e45ce82b0)
- [StudentSchema에서 버전키 제거](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/64864b3f33fb69752cd19dfd77ec7cd8b1808dc5)

♻️ Refactor/#32 회원가입시 전화번호 추가로 입력받기

---

back/db/classroomInfo.js
back/routes/classroomInfo.js
back/routes/reservation.js
back/routes/reserveRoom.js
back/server.js

#41 
요일 매핑 완료
건물, 호수 매핑완료
포스트맨 테스트 완료
class디비 안에 classroom_idx가 비427, 새빛103 이런식으로 되어 있어서 직접 매핑을 사용함
비427 -> 비마관, 427호로 분리
+ 화도관이 "화~"인지 "화도~"인지는 확인이 필요함
const buildingMap = {
"복지관": "복",
"비마관": "비",
"새빛관": "새빛",
"연구관": "연",
"옥의관": "옥",
"참빛관": "참",
"한울관": "한울",
"화도관": "화",
"80주년 기념관": "기",
"미지정": null,
"": null
};

♻️ check-time api 수정, 건물 호수 매칭 완료

---

back/routes/classroomInfo.js

#43 
classroom-info api 생성
프론트가 {
"building": "기념관",
"room": "201호"
}
를 보냈을때, 백엔드에서 [{equipment, minNumberOfUsers, contactDepartment, contactLocation, contactNumber}] 응답
#41 브랜치에서 실수로 진행해버림, 그래서 Feat/#43 브랜치에 내용 merge 후 이것만 PR올림

✨ classroom-info api 생성, 강의실 정보 불러오기 완성

---

back/routes/reservation.js
back/routes/reserveRoom.js
front/src/api/make-reservation/fetchTimeList.ts
front/src/pages/MakeReservation/MakeReservation.tsx

#46 
- [check-room API 응답 형식 수정: rooms 배열로 반환](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/a32bc41de1c12d7b70e61f301ddd5237c52028f8)
- [fetchTimeList 함수에 날짜 매개변수 추가 및 MakeReservation 컴포넌트에서 호출 방식 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/372cd4fc0ced2f1e47d1ee96f4bd47a385a38320)
- [기념관, 누리관 맵핑 누락 보완](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/25b004666378fd697a6c3dcaf14c12e5d9608a1a)

🐛 Refactor/#46 예약 페이지 FE-BE 요청/응답 데이터 형식 맞추기

---

front/src/components/Popup/AlertPopup.tsx
front/src/pages/MakeReservation/MakeReservation.tsx

#35
- [AlertPopup 컴포넌트 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/pull/49/commits/edc9c923a98cc4de4047121840ae49b66f0d5a95)
- [AlertPopup 컴포넌트의 인터페이스 및 함수 이름 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/pull/49/commits/6b06cd675954ab43a25fe9eb16d485da6c7ce81a)
- [lertPopup 컴포넌트를 MakeReservation 페이지에 추가하고 스타일 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/pull/49/commits/7c9901e14d16cbf4d14842fdc0851b1dfc815519)

✨ Feat/#35 AlertModal 컴포넌트 만들기

---

front/src/App.tsx
front/src/api/mypage/dto/fetchProfileDataDto.ts
front/src/api/mypage/fetchProfileData.ts
front/src/api/profile-detail/deleteUserAccount.ts
front/src/api/profile-detail/dto/updateUserInformationDto.ts
front/src/api/profile-detail/updateUserInformation.ts
front/src/components/Input.tsx
front/src/constants/routes.ts
front/src/pages/MyPage/components/ProfileCard.tsx
front/src/pages/ProfileDetail/ProfileDetail.tsx
front/src/pages/ProfileDetail/components/ProfileActions.tsx
front/src/pages/ProfileDetail/components/ProfileForm.tsx

#52 
- [fetchProfileDataDto에서 예약 상태 필드 제거 및 이메일, 전화번호 필드 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/3e83f7d0a99418cdfd0d699a1c737366092866e6)
- [프로필 상세 페이지 추가 및 라우터 설정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/e851c20ee8d36912909facd7f7db656dc1e66d10)
- [프로필 상세 버튼 클릭시 상세페이지로 이동](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/d8e7595746f848d6720f93a8897db79995f2cac7)
- [Input 컴포넌트에 레이블 및 읽기 전용 속성 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/06167d4170391763c46fbd22c37ac2d5263d66d0)
- [프로필 상세 페이지 및 관련 컴포넌트 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/1b2cbbf5eb1519c2ec897156c0386ffa92ce0e31)
- [axios를 fetch로 변경하여 마이페이지 데이터 가져오기 함수 수정 및 데모 데이터 이름 …

✨ Feat/#52 마이페이지 프로필 수정 및 탈퇴하기

---

back/routes/reservation.js

#55 
checktime에서 예약된 정보 불러오는거 수정함
예약 완료 후 해당 사항이 반영되어서 나타나는지 확인
<해결 전>
예약이 되어 있음에도 빈배열로 와지는 문제 발생
<해결 후>

check time 오류 수정

---

back/routes/makereserve.js

#55 
시스템 상 중복 예약 시 conflict 생기도록 설정
중복 예약한다면, 409 conflict 생기면서 {  "message": "해당 시간에 이미 예약이 존재합니다." }라고 보내줌
<처음 예약 시>
<중복 예약 시>

중복 예약 시 409 conflict

---

back/routes/updatereserve.js
back/server.js

#55 
예약 수정하기 기능 완료
포스트맨으로 원하는 수정 내용 전송하면 디비가 수정됨. 바뀐 정보가 프론트에 잘 보임
<원래 예약>
<postman 테스트 결과>

update reservation 생성

---

back/routes/deletereserve.js
back/server.js

#55 
예약 삭제 기능 완료
예약해놨던 id로 포스트맨 테스트 해봄
<전 PR에서 업데이트 한 예약이 사라진 사진>
<포스트맨>

예약 삭제 기능 완료

---

back/routes/getreserve.js
back/server.js

#55 
getreserve.js에 reservationid받으면, 관련 정보 보내주도록 설정
프론트는 reservationid 보내주기
백엔드는 reservationid 받으면,
{ "studentId": "2022204062", "date": "2025-04-02", "building": "새빛관", "room": "101호", "startTime": "13:00", "endTime": "14:30", "purpose": "프로젝트 회의", "professor": "담당교수명", "participantCount": 3}
정보 보내주기

✨ get-reservation 기능 완료

---

front/src/api/room-schedule/dto/fetchReservationSchedulesDto.ts
front/src/api/room-schedule/fetchReservationSchedules.ts
front/src/components/Input.tsx
front/src/constants/routes.ts
front/src/pages/Home/components/NavigationButtons.tsx
front/src/pages/ReservationStatus/ReservationStatus.tsx

#61
- [예약 상태 버튼의 라벨 "강의실 사용 현황"으로 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/cf4c55c52d71231603b3e4574c4fff4771968cdb)
- [예약 상태 라벨 "강의실 사용 현황"으로 수정](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/c03bcab7491b999562c33d1b6e23a81b4360e449)
- [Input 컴포넌트의 스타일 수정: 날짜 입력 시 텍스트 중앙 정렬 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/fe41ca54fc1080f231891d597fd9fb04ff027084)
- [예약 스케줄을 가져오는 기능을 위한 DTO 및 API 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/e0332e5ed0d44bd55c56f741da892032c623ca39)
- [예약 현황 페이지 개선: 강의실 선택 및 예약 데이터 로드 기능 추가](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/be24719cdc1ebb0c73f9316f3e52b0f624b17663)

✨ Feat/#61 강의실 사용 현황 페이지 api 연동 함수 및 마크업개발

---

front/src/api/make-reservation/getReservation.ts

🔧 Feat/#54 API 경로 수정: 예약 조회 API의 경로를 변경하여 일관성 유지

---

back/routes/deleteUser.js
back/routes/updateUser.js
back/routes/userInfo.js
back/server.js

#66 
유저 정보 불러오기
정보 수정하기
탈퇴하기
[정보 수정 테스트 완료]
https://github.com/user-attachments/assets/46639fef-3bc2-4dfe-bf99-32077cb021f1
[탈퇴 테스트 완료]
https://github.com/user-attachments/assets/32bce45f-a432-4d21-9699-98f6648267cb

✨ User 정보 불러오기/수정/탈퇴

---

front/src/api/room-schedule/fetchReservationSchedules.ts
front/src/pages/ReservationStatus/ReservationStatus.tsx

#72 
- [예약 일정 조회 API에 날짜 파라미터 추가, 예약 상태 페이지에서 해당 파라미터 사용](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/762ad8536060c6a9d72c2e7e844c98364a771a6d)
- [예약 상태 페이지에서 사용자 이름 익명화 기능 추가 및 UI 개선](https://github.com/kw-chi-community/CHIC-25-CLASSROOM-STUDENT/commit/a0e05bcedfa4ea3a59fd65084047e7fa0df58257)
-> 아직 백엔드 연결 전

Refactor/#72 classroom-reservatoin api 요청 및 응답 타입 수정

---

back/routes/classroomReservation.js
back/routes/getreserve.js
back/server.js

#55 
강의실이랑 호실 알려주면, 요일이랑 시간 예약 정보 및 강의 정보를 한번에 보내줌
날짜 프론트에서 보내주면 해당하는 날에만 정보 가져오는 걸로 수정함.
{
"building": "기념관",
"room": "201호"
"date":"2025-04-17"
}
을 받으면,
[
{
"type": "reservation",
"start_time": "09:00",
"end_time": "10:30",
"user": "정수진",
"purpose": "스터디",
},
{
"type": "lecture",
"start_time": "11:00",
"end_time": "12:30",
"subject": "자료구조".
"professor": "조민수"
}
]
으로 답해줌
[해당 강의실이 강의도 있고 예약도 있을 때]
[날짜에 따라서 나오는 결과]

✨ classroom-reservation 완료

---

back/routes/classroomInfo.js
back/routes/classroomReservation.js
back/routes/getreserve.js
back/routes/makereserve.js
back/routes/noticeDetail.js
back/routes/reservation.js
back/routes/reservationDetail.js
back/routes/reservationList.js
back/routes/reserveRoom.js
back/routes/showPopup
back/routes/updatereserve.js
back/routes/userInfo.js

#74 
아래 api에 토큰 인증 적용
•	/api/reservation-list
•	/api/reservation-detail
•	/api/notice-detail
•	/api/show-notice-popup
•	/api/check-room
•	/api/check-time
•	/api/classroom-info
•	/api/make-reservation
•	/api/get-reservation
•	/api/classroom-reservation
•	/api/user-info
포스트맨 테스트 완료
| 기능 | 스크린샷 |
| :--: | :------: |
|      |          |

✨ JWT 토큰 POST API에 반영
